server:
  port: 8761
erueka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
security:
  basic:
    enabled: true
---
spring:
  profiles: default
server:
  port: 8761
security:
  user:
    name: discovery
    password: 3GfhPZQifTpVcu
---
spring:
  profiles: local
server:
  port: 8761
security:
  user:
    name: discovery
    password: 3GfhPZQifTpVcu
---
spring:
  profiles: dev
server:
  port: 8761
security:
  user:
    name: discovery
    password: 3GfhPZQifTpVcu
---
spring:
  profiles: prd
server:
  port: 8761
security:
  user:
    name: discovery
    password: 3GfhPZQifTpVcu
