eureka:
  host: 127.0.0.1
  port: 8761
  username: discovery
  password: 3GfhPZQifTpVcu
  client:
    service-url:
      defaultZone: http://${eureka.username}:${eureka.password}@${eureka.host}:${eureka.port}/eureka
---
spring:
  profiles: default
eureka:
  host: 127.0.0.1
---
spring:
  profiles: dev
eureka:
  host: eureka
---
spring:
  profiles: prd
eureka:
  host: eureka