server:
  port: 8002
flyway:
  table: oauth-schema-version
oauth2:
  private-key:
    path: "jwt_keypair.jks"
    alias: "jwt"
    password: "KCPzQVp8VVyHV9Ds"
  access-token:
    expire_in: 720  #accessToken有效期 30 天（720小时）
spring.profiles.include:
  - flyway
  - mysql
---
spring:
  profiles: default
server:
  port: 8002
---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: prd
server:
  port: 8080
