server:
  port: 8004
flyway:
  table: todo-schema-version
swagger:
  service-name: "任务服务"
  service-desc: "管理卡片及任务信息"
spring.profiles.include:
  - undertow
  - flyway
  - mysql
  - rabbit
  - swagger
  - jwt
  - feign
---
spring:
  profiles: default
server:
  port: 8004
---
spring:
  profiles: dev
server:
  port: 8080
---
spring:
  profiles: prd
server:
  port: 8080
